name: Android Build and Deployment Pipeline for Staging

on:
  workflow_run:
    workflows: [ "Run Tests on Push" ]
    branches: [ develop ]
    types:
      - completed
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.STAGING_KEYSTORE }}
        run:
          TMP_KEYSTORE_FILE_PATH="${GITHUB_WORKSPACE}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/staging.jks
      - name: Decode Keystore Properties
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_PROPERTIES }}
        run:
          echo $ENCODED_STRING | base64 -di > "${GITHUB_WORKSPACE}"/keystore.properties
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Generate app APK.
        run: ./gradlew assembleStaging --stacktrace
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/