# Name of your workflow
name: Run Tests on Push
# Define on which Github event, workflow will trigger
on: [push]
jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Decode Keystore Properties
        env:
          KEYSTORE_PROPERTIES_STRING: ${{ secrets.KEYSTORE_PROPERTIES }}
        run:
          echo KEYSTORE_PROPERTIES_STRING > "${GITHUB_WORKSPACE}"/keystore.properties
      - name: Add google-services.json
        env:
          GOOGLE_SERVICES_STRING: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run:
          echo $GOOGLE_SERVICES_STRING > "${GITHUB_WORKSPACE}"/app/google-services.json
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run Tests
        run: ./gradlew test